[tool.poetry]
name = "speedtest"
version = "0.1.0"
description = ""
authors = ["István Siroki <stevesiroki@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
speedtest-cli = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
